### ISSUE TITLE
What happened to tree shaking?

### ISSUE THREAD

**Issue by ElPapi42** [alfonsobries/vue-tailwind#105]
Hello there!

First, thanks for this awesome library!

I'm using VueTailwind with Nuxt, and I have a problem, I don't find anything on the docs about tree shaking, actually, the plugin is bloating my build with 310kb.

I found a PR from the past year that includes this feature in the project, but now I see nothing, can you give me some light on this?

Thanks in advance for your support, I feel I'm missing something obvious but I already spent 6 hours looking for this xD

**Comment by alfonsobries** [comment]
@ElPapi42 Ok this is an issue that I am aware of, currently, it is indeed possible to import only the components you need, to do it use this syntax:

```js
import ComponentName from 'vue-tailwind/dist/components/{ComponentName}.umd'
Vue.use(ComponentName, {
  classes: 'xxxx',
  // ...
})
```

Changing component name for the name of the component:

```js
import TInput from 'vue-tailwind/dist/components/TInput.umd';
import TAlert from 'vue-tailwind/dist/components/TAlert.umd';
Vue.use(TInput, {
  classes: 'xxxx',
  // ...
})

Vue.use(TAlert, {
  classes: 'xxxx',
  // ...
})
```

That will make your build smaller if you only need a few components but if you import a couple more it will actually increase the size since the components may have duplicated code.

This is not documented because I am not happy with the approach I follow and it's something I improved a lot in the v2 that I am about to release (https://github.com/alfonsobries/vue-tailwind/pull/102) but the "perfect" solution that I have in my mind will be released until v3.

So another alternative is that you use the v2 that it's pretty much the same as v1 but the syntax for installing the components changed a little.

The steps to use this new version (notice that is still beta) is to run `npm install vue-tailwind@next` and installing following this format (notice that I am only importing a few components but all of them are available

```
import Vue from 'vue'
import VueTailwind from 'vue-tailwind'
import TInput from 'vue-tailwind/dist/t-input'
import TButton from 'vue-tailwind/dist/t-button'
import TModal from 'vue-tailwind/dist/t-modal'

const settings = {
  't-input': {
    component: TInput,
    props: {
      classes: 'border-2 block w-full rounded text-gray-800'
      // ...More settings
    }
  },
  't-button': {
    component: TButton,
    props: {
      classes: 'rounded-lg border block inline-flex items-center justify-center'
      // ...More settings
    }
  },
  't-modal': {
    component: TModal,
    props: {
      classes: {
        body: 'bg-white p-3',
        header: 'p-3',
        footer: 'p-3 border-t'
      }
      // ...More settings
    }
  }

}

Vue.use(VueTailwind, settings)
```

**Comment by ElPapi42** [comment]
Awesome explanation, I will try 2.0! Thanks for your support!
