### ISSUE TITLE
Feature Request: Datatables 

### ISSUE THREAD

**Issue by mous2890** [alfonsobries/vue-tailwind#114]
It would be amazing to have a Vue Tailwind Datatables component with built in search box, filters, multi column select.

A great template to start with is https://tailwindcomponents.com/component/table-responsive-with-filters

**Comment by alfonsobries** [comment]
@mous2890 This is something I probably will add sooner or later but not in my immediate priorities since I want to spend more time in the Vue3 version of this package, still ill keep it in mind

Still, the table component (https://www.vue-tailwind.com/docs/table) is flexible enough to add those features manually (i know this request is not about that)

Thanks!
