### ISSUE TITLE
Benefit of this package?

### ISSUE THREAD

**Issue by webcoderkz** [alfonsobries/vue-tailwind#45]
It looks to me, like you're reinventing another Bootstrap/Bulma, etc. I think many people would choose tailwind just for simplicity of class utilities. Could you share your thoughts, when you created this project?

**Comment by Kawacrepe** [comment]
I mean the creator wanna develop something which can be adapted but I'm not sure of the way he took.
Imo starting to develop a vue renderless library would have been better.

**Comment by alfonsobries** [comment]
Correct the idea is that the user can define how the components will look like from the beginning instead to have a default theme that everyone that uses your library has to use like Bootstrap or Bulma.

I'm working in the next version of this package and that it's even more flexible it has a default render method because I want something that just works, still, this new version makes it easy to override the render method so is even more flexible  https://v1.vue-tailwind.com/
