### ISSUE TITLE
Best practice to open a modal from within a modal?

### ISSUE THREAD

**Issue by raisonon** [alfonsobries/vue-tailwind#61]
Is this the best method to open another modal from within a modal? First close and then open?

There is a bit of flash as this happens and I wonder if there is a better way to approach this?

Thanks

                
```
<button
  class="underline text-sblue-500"
  @click="$refs.modalLogin.hide(); $modal.show('modal-forgotten');"
 >Forgotten Password?</button>```

**Comment by alfonsobries** [comment]
@raisonon yeah I understand the issue, the problem is that the HTML of the modal is inside the parent modal so that may cause issues, that's something I want to fix in the next version of the package, vue3 has a new feature called teleport that is perfect to solve that problem.

Anyway...

If you don't need to have both modals opened I think that's the best way, however, I would put that inside a method, you can also use nextTick() method to wait until the other modal is closed

thinking in something like that:

```
<button
  class="underline text-sblue-500"
  @click="methodForOpenModal"
 >Forgotten Password?</button>```
```

```
methods: {
  methodForOpenModal() {
    this.$modal.hide('modal-1');
    this.$modal.show('modal-2');
 },
// Option 2 add next tick to wait for the modal to be hidden (not tested)
async methodForOpenModal() {
    this.$modal.hide('modal-1');
await this.$nextTick()
    this.$modal.show('modal-2');
 },
// Option 3 use the closed event in the parent modal (not tested)
methodForOpenModal() {
   this.$refs.modal.$on('closed', () => {
     this.$modal.show('modal-2');
    })

     this.$modal.hide('modal-1');
 }
}
```

**Comment by alfonsobries** [comment]
@raisonon not sure if your case but in general is better to not put a modal inside another modal but add the modal outside and open/hide using the name 

<t-modal name="modal-1">
</t-modal>

<t-modal name="modal-2">
</t-modal>

**Comment by raisonon** [comment]
Thanks for the help on this. Nice idea about nextTick -- will look into doing that.

I had modals next to each other but not inside one another.

My only feedback would be it might be good to push this logic into the core package, but it's probably quite low prioirty and tbh It's a bit lazy of me not to create my own methods!

Thanks for quick reply and great work as usual.

**Comment by alfonsobries** [comment]
@raisonon thanks!
