### ISSUE TITLE
Tabs/Collapse component

### ISSUE THREAD

**Issue by gaetansenn** [alfonsobries/vue-tailwind#80]
Hello,

I'm using vue-tailwind for a new e-commerce projet and I would like to help you implement the tabs and also collapse component. Do you have a trello to see upcoming and current progress work ?
I'm available here : gaetan.senn@gmail.com

PS: Nice work for this projet

**Comment by alfonsobries** [comment]
Hi, @gaetansenn just sent you an invite, for the moment ignore the cards in Spanish this is an old board that I not used in a long time, ill update this with the current status/tasks of this project.

I don't have any special way to handle this project since I am the only active contributor but if some fulks like you joins we can discuss ways to communicate and manage this project.

**Comment by alfonsobries** [comment]
@gaetansenn Update: I removed old info and created the first scratch of a new board
