### ISSUE TITLE
Nuxt Component support

### ISSUE THREAD

**Issue by lights0123** [alfonsobries/vue-tailwind#92]
[Nuxt Components](https://github.com/nuxt/components) automatically allow all components in an app to use other components without importing them—the source files are scanned, and used components are automatically imported. This allows for tree shaking without manually importing each component. A simple starting point for this library is creating the file `nuxt.js` in the root directory:

```js
import { join } from 'path'

export default function () {
  this.nuxt.hook('components:dirs', (dirs) => {
    // Add ./components dir to the list
    dirs.push({ path: join(__dirname, 'src/components') }, { path: join(__dirname, 'src/inputs') });
  });
}
```

Then, users of the library can opt-into it by adding `vue-tailwind` in Nuxt's `buildModules` config. Some work will need to be done for adding configuration.

**Comment by alfonsobries** [comment]
@lights0123 the components need to be installed within the plugin because some of the props (like the variant and classes related) are override in the installation process.

That means made something like that will not work

For version 3 of the library I planning to make the component self-installable so this can be considered again but currently is not possible.
