### ISSUE TITLE
Vanilla components losing class on Nuxt

### ISSUE THREAD

**Issue by sergiooak** [alfonsobries/vue-tailwind#93]
New components (Date picker, Toggle, etc) works just fine  but older ones works only partial, all HTML and JS works, but it does not have any classes.

1 - Plugin and Import
![image](https://user-images.githubusercontent.com/46563926/96919302-f80efa80-1481-11eb-9254-e81f40b0363e.png)
![image](https://user-images.githubusercontent.com/46563926/96919389-12e16f00-1482-11eb-837b-d4dfd6e99c21.png)

2 - Using new components
![image](https://user-images.githubusercontent.com/46563926/96919617-65bb2680-1482-11eb-89ff-0026ff67b812.png)
![image](https://user-images.githubusercontent.com/46563926/96919610-618f0900-1482-11eb-8533-686281265043.png)
![image](https://user-images.githubusercontent.com/46563926/96919668-7bc8e700-1482-11eb-8081-5f2db21dcdb0.png)

3 - using "older" components
![image](https://user-images.githubusercontent.com/46563926/96919727-9307d480-1482-11eb-8c45-7a83460706d1.png)
![image](https://user-images.githubusercontent.com/46563926/96919756-9c913c80-1482-11eb-97d5-7661deb1779e.png)
![image](https://user-images.githubusercontent.com/46563926/96919827-b6cb1a80-1482-11eb-9faf-b0712a138569.png)

---

On the Props of new components default calsses are setted, but on old one it's not
`vue-tailwind/src/components/TToggle.ts`
![image](https://user-images.githubusercontent.com/46563926/96920957-3f968600-1484-11eb-82fa-961eedaff57d.png)

`vue-tailwind/src/components/TCard.ts /`
![image](https://user-images.githubusercontent.com/46563926/96921024-563cdd00-1484-11eb-8175-136d0b020af9.png)

**Comment by alfonsobries** [comment]
@sergiooak that is not exactly an error but maybe is not well explained in the Docs

Most of the components don't have any class by default, and it because the vision of this package is to not decide a theme for you since you are intended to create your own theme depending on your app.

The ones that have classes are because have the minimum amount of classes to work, the toggle is a good example, it needs some sets of classes to work fine otherwise you will see just a set of divs and spans.

Note: You are not the first person that ran into this issue, for the next version I probably will add a default theme but meanwhile you can use the Theme Builder https://www.vue-tailwind.com/theme-builder to create a theme.

Let me know if I can help you

**Comment by sergiooak** [comment]
Got it! It works fine after I "created" a theme (just skipped every step xD), but I really enjoy the Default Theme idea, I believe many people will use it "as is"
